directory/urls.py
"""Copyright Askbot SpA 2014, Licensed under GPLv3 license."""

from django.conf.urls import url
from directory import views
from django.contrib.admin.views.decorators import staff_member_required

urlpatterns = (
    url(r'^$', views.index, name='directory_index'),
    url(r'^list/$', views.list_directory, name='directory_list'),
    url(r'^download-file/(?P<file_name>.*)/$', views.download_file, name='directory_download_file'),
    url(r'^list1/$', staff_member_required(views.list_directory, login_url="/admin/"), name='d_test'),
)

UserStatistics/models.py
from django.db import models

# Create your models here.

ExperimentBasics/forms.py
__author__ = 'A. K. Fischer'

from django import forms
from django.core.exceptions import ValidationError
from ExperimentBasics.models import *


def validateExperimentFileExtension(value):
    """ Validate that uploaded experiment file is in Excel format. """
    if not (value.name.endswith(".xlsx")):
        raise ValidationError(u'Only Excel files (.xlsx) allowed!')


def validatePNGImage(value):
    if not (value.name.endswith(".png")):
        raise ValidationError(u'Only png files (.png) allowed!')


class UploadExperimentFileForm(forms.Form):
    """
    Upload experiment file form for Admin Panel.
    """
    txtFileDescription = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    file = forms.FileField(required=False, validators=[validateExperimentFileExtension])
    medal = forms.ImageField(required=False, validators=[validatePNGImage])


class UploadMedalForm(forms.Form):
    """
    Upload medal for an already-existing experiment.
    """
    experiment_id = forms.ModelChoiceField(queryset=Experiment.objects.all(), empty_label="select experiment")
    medal = forms.ImageField(required=True, validators=[validatePNGImage])


class NewsManagementForm(forms.Form):
    """
    Add news form for Admin Panel.
    """
    txtNewsDescriptionEn = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=True)
    txtNewsDescriptionDe = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=False)
    txtNewsDescriptionRu = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=False)
    txtNewsDescriptionBg = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=False)
    txtNewsDescriptionUk = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=False)
    txtNewsDescriptionCs = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=False)
    txtNewsDescriptionPl = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=False)
    txtNewsDescriptionHr = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=False)
    txtNewsDescriptionSr = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=False)
    txtNewsDescriptionSk = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=False)

    txtNewsDescriptionMk = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=False)
    txtNewsDescriptionSl = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=False)

    txtNewsDescriptionBs = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=False)

    priority = forms.ChoiceField(choices=[(i, i) for i in range(11)])

    news_id = forms.CharField(widget=forms.HiddenInput(attrs={'value':0}))


class MultilingualGenderManagementForm(forms.Form):
    """
    Multilingual gender management form for Admin Panel.
    """
    txtGenderEn = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtGenderDe = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtGenderRu = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtGenderBg = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtGenderUk = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtGenderCs = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtGenderPl = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtGenderHr = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtGenderSr = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtGenderSk = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtGenderMk = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtGenderSl = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtGenderBs = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    gender_id = forms.CharField(widget=forms.HiddenInput(attrs={'value':0}))
    
    
class MultilingualEducationDegreeManagementForm(forms.Form):
    """
    Multilingual education degree management form for Admin Panel.
    """
    txtEducationDegreeEn = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtEducationDegreeDe = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtEducationDegreeRu = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtEducationDegreeBg = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtEducationDegreeUk = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtEducationDegreeCs = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtEducationDegreePl = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtEducationDegreeHr = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtEducationDegreeSr = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtEducationDegreeSk = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtEducationDegreeMk = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtEducationDegreeSl = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtEducationDegreeBs = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    degree_id = forms.CharField(widget=forms.HiddenInput(attrs={'value':0}))
    
    
class MultilingualLanguageManagementForm(forms.Form):
    """
    Multilingual language management form for Admin Panel.
    """
    txtLanguageCode = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtLanguageEn = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtLanguageDe = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtLanguageRu = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtLanguageBg = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtLanguageUk = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtLanguageCs = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtLanguagePl = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtLanguageHr = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtLanguageSr = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtLanguageSk = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtLanguageMk = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtLanguageSl = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    txtLanguageBs = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    language_id = forms.CharField(widget=forms.HiddenInput(attrs={'value':0}))

    
class ExperimentInfoManagementForm(forms.Form):
    """
    Add experiment info form for Admin Panel.
    """
    txtExperimentInfoEn = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=True)
    txtExperimentInfoDe = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=False)
    txtExperimentInfoRu = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=False)
    txtExperimentInfoBg = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=False)
    txtExperimentInfoUk = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),
                                           required=False)
    txtExperimentInfoCs = forms.CharField(widget=forms.Textarea(attrs={'rows': 1,'cols':50, 'class': 'form-control'}),

templates/adminpanel/AddAudio.html
{% extends "adminpanel/Base.html" %}
{% load i18n %}
{% block content %}

<style type="text/css">
    h1, h2, h3, h4 {
        color: green;
        font-weight: bold;
    }

    .bg-hover:hover {
        background-color: whitesmoke;
    }

    .highlight {
    	background-color: #99b2d2;
    }
</style>

	<div class="content-div col-lg-12 col-xs-12 task-background" style="padding-top:50px;">


		<div class="row">
	        <div class="col-md-12">
	            <h2><u> Update Audio File</u></h2>
	            <p style="color: #5f2121;"> To remove the audio file set "Has Audio" field to "No" and <b>Submit</b> </p>
	        </div>
	    </div>
		<div class="row">
			<div class="col-md-8">

				<form method="POST" action="" enctype="multipart/form-data">
					{% csrf_token %}
					{{ form.as_p }}
					<button type="sumbit" class="btn btn-primary">Submit</button>
					
				</form>
			</div>
		</div>

		

	</div>

	
	
	{% if questions_list %}
		<div class="row margin-top">
		<div class="panel panel-default">
			<div class="panel-heading">
				
				<h4><b style="color: blue;"> {{ exp_type }}</b> Experiments list for <i style="color: blue;">Native {{ native_lang }}</i> to <i style="color: blue;"> Foreign {{ foreign_lang }}</i></h4>
				{% if link %}
				<a href="{{ link }}"><b> Download CSV </b></a>
				{% endif %}

			</div>
			<div class="panel-body">
				<table class="table table-sm table-striped" id="table1">

					<thead>
						<th>#</th>
						<th>Foreign Word</th>
						<th>Has Audio</th>
						<th>Audio File</th>
						
					</thead>	
					<tbody>

						

						{% for id, word, has_audio, path in  questions_list %}
						<tr>
							<td>{{ id }}</td>
							<td>{{ word }}</td>
							<td>{{ has_audio }}</td>
                            
							<td>
								<audio id="" controls> 
			                        <source id="" src="test" type="audio/mp3">
			                    </audio>
                                <form class="form-inline" id="form_{{ id }}" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-group col-md-2">
                                        <label>{{ path }} </label>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <input type="text" name="filename" >
                                    </div>
                                    <div class="form-group col-md-3">
                                        <button type="button" onclick="uploadAudioFile({{ id }})">Add</button>
                                    </div>
                                </form>
                            </td>
										

						</tr>
						{% endfor %}

						
					</tbody>
					
					

				</table>
			</div>
		</div>
	</div>

	{% else %}
	<div class="row margin-top">
		<div class="panel panel-default">
			{%if native_lang %}
			<h4 style="text-align: center;">No Experiment found for <i style="color: blue;">Native {{ native_lang }}</i> to <i style="color: blue;"> Foreign {{ foreign_lang }}</i></h4>
			{% else %}
			<h4 style="text-align: center;">Search to get User mean Intelligibility Score for Experiments</h4>
			{% endif %}
		</div>
	</div>

	{% endif %}
	    

</div>



{% endblock %}

{% block scripts %}

	{% load staticfiles %}

	<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'pace/themes/blue/pace-theme-bounce.css' %}">
	<script type="text/javascript" src="{% static 'pace/pace.js' %}"></script>
	<script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js "></script>

    

    <script type="text/javascript">


    	$(document).ready(function() {

	    	$('#table1').DataTable({
	    		"paging" : true,
	    		"order": [] 
	    	});
	    	
	    	// $("#total_avg").html("Test");

            var selectedExp = 0;






				
		} );

    </script>

{% endblock %}

templates/adminpanel/EducationDegreeManagement.html
{% extends "adminpanel/Base.html" %}
{% load i18n %}
{% block content %}

    <style type="text/css">
        h1, h2, h3, h4 {
            color: green;
            font-weight: bold;
        }

        .bg-hover:hover {
            background-color: whitesmoke;
        }
    </style>

    <div class="content-div col-lg-12 col-xs-12 task-background" style="padding-top:50px;">
        <form id="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="row">
                <div class="col-md-12">
                    <h2><u> Multilingual Education Degree Management</u></h2>
                </div>
            </div>


            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Education Degree in English :</label>
                </div>
                <div class="col-md-4">
                    {{ form.txtEducationDegreeEn }}
                    {{ form.degree_id }}
                </div>
                <div class="col-md-1">
                    <span style="color:red;">*</span>
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Education Degree in German :</label>
                </div>
                <div class="col-md-4">
                    {{ form.txtEducationDegreeDe }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Education Degree in Russian :</label>
                </div>
                <div class="col-md-4">
                    {{ form.txtEducationDegreeRu }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Education Degree in Bulgarian :</label>
                </div>
                <div class="col-md-4">
                    {{ form.txtEducationDegreeBg }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Education Degree in Ukrainian :</label>
                </div>
                <div class="col-md-4">
                    {{ form.txtEducationDegreeUk }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Education Degree in Czech :</label>
                </div>
                <div class="col-md-4">
                    {{ form.txtEducationDegreeCs }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Education Degree in Polish :</label>
                </div>
                <div class="col-md-4">
                    {{ form.txtEducationDegreePl }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Education Degree in Croatian :</label>
                </div>
                <div class="col-md-4">
                    {{ form.txtEducationDegreeHr }}
                </div>
            </div>


            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Education Degree in Bosnian :</label>
                </div>
                <div class="col-md-4">
                    {{ form.txtEducationDegreeBs }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Education Degree in Serbian :</label>
                </div>
                <div class="col-md-4">
                    {{ form.txtEducationDegreeSr }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Education Degree in Slovak :</label>
                </div>
                <div class="col-md-4">
                    {{ form.txtEducationDegreeSk }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Education Degree in Macedonian :</label>
                </div>
                <div class="col-md-4">
                    {{ form.txtEducationDegreeMk }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Education Degree in Slovenian :</label>
                </div>
                <div class="col-md-4">
                    {{ form.txtEducationDegreeSl }}
                </div>
            </div>

            <div class="row margin-top">

                <div class="col-md-4">
                    <input id="btnSave" type="submit" value="Save" class="btn btn-primary"
                           onclick="return isValidateForm();">

                </div>
            </div>
        </form>


        <div class="row margin-top">
            <div class="col-md-12">
                <table class="datatable">
                    <thead>
                    <th>Education Degree</th>
                    <th>Update</th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>

            </div>
        </div>

    </div>
{% endblock %}

{% block scripts %}

    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.js"></script>

    <script language="JavaScript">
        $(document).ready(function () {

            var oTable = $('.datatable').dataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "{% url 'multilingual_degree_management_gridview' %}"
            });

        });

        function redirectTo(URL) {
            window.location.href = '/' + URL;
        }

        function isValidateForm() {
            var degreeEn = $('#id_txtEducationDegreeEn');

            if (degreeEn.val() == '') {
                alert("Education Degree in English is required.");
                return false;
            }
            else {
                return true;
            }
        }

    </script>

{% endblock %}

templates/adminpanel/ExperimentInfoManagement.html
{% extends "adminpanel/Base.html" %}
{% load i18n %}
{% block content %}

    <style type="text/css">
        h1, h2, h3, h4 {
            color: green;
            font-weight: bold;
        }

        .bg-hover:hover {
            background-color: whitesmoke;
        }
    </style>

    <div class="content-div col-lg-12 col-xs-12 task-background" style="padding-top:50px;">
        <form id="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="row">
                <div class="col-md-12">
                    <h2><u> Experiment Info Section Management</u></h2>
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Experiment Info in English :</label>
                </div>
                <div class="col-md-7">
                    {{ form.txtExperimentInfoEn }}
                    {{ form.experiment_info_id }}
                </div>
                <div class="col-md-1">
                    <span style="color:red;">*</span>
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Experiment Info in German :</label>
                </div>
                <div class="col-md-7">
                    {{ form.txtExperimentInfoDe }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Experiment Info in Russian :</label>
                </div>
                <div class="col-md-7">
                    {{ form.txtExperimentInfoRu }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Experiment Info in Bulgarian :</label>
                </div>
                <div class="col-md-7">
                    {{ form.txtExperimentInfoBg }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Experiment Info in Ukrainian :</label>
                </div>
                <div class="col-md-7">
                    {{ form.txtExperimentInfoUk }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Experiment Info in Czech :</label>
                </div>
                <div class="col-md-7">
                    {{ form.txtExperimentInfoCs }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Experiment Info in Polish :</label>
                </div>
                <div class="col-md-7">
                    {{ form.txtExperimentInfoPl }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Experiment Info in Croatian :</label>
                </div>
                <div class="col-md-7">
                    {{ form.txtExperimentInfoHr }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Experiment Info in Bosnian :</label>
                </div>
                <div class="col-md-7">
                    {{ form.txtExperimentInfoBs }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Experiment Info in Serbian :</label>
                </div>
                <div class="col-md-7">
                    {{ form.txtExperimentInfoSr }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Experiment Info in Slovak :</label>
                </div>
                <div class="col-md-7">
                    {{ form.txtExperimentInfoSk }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Experiment Info in Macedonian :</label>
                </div>
                <div class="col-md-7">
                    {{ form.txtExperimentInfoMk }}
                </div>
            </div>

            <div class="row margin-top">
                <div class="col-md-3">
                    <label>Experiment Info in Slovenian :</label>
                </div>
                <div class="col-md-7">
                    {{ form.txtExperimentInfoSl }}
                </div>
            </div>

            <div class="row margin-top">

                <div class="col-md-4">
                    <input id="btnSave" type="submit" value="Save" class="btn btn-primary"
                           onclick="return isValidateForm();">

                </div>
            </div>
        </form>


        <div class="row margin-top">
            <div class="col-md-12">
                <table class="datatable display">
                    <thead>
                    <th>ID</th>
                    <th>Experiment Info</th>
                    <th>Created On</th>
                    <th>Update</th>
                    <th>Delete</th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>

            </div>
{#            <div><a onclick="deleteAllExperimentInfo();">Delete ALL Experiment Info</a>#}
{#            </div>#}
        </div>

    </div>
{% endblock %}

{% block scripts %}

    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.js"></script>

    <script language="JavaScript">
        $(document).ready(function () {

            var oTable = $('.datatable').dataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "{% url 'experiment_info_section_management_gridview' %}"
            });

        });

{#        function deleteAllExperimentInfo() {#}
{#            if (confirm("Really delete ALL experiment info ?")) {#}
{#                var reply = prompt("Please type 'delete ALL' to confirm deletion.", '');#}
{#                if (reply == 'delete ALL') {#}
{#                    alert("Deleting all experiment info...");#}
{#                    var obj = {type: 2};#}
{#                    processAjaxRequest(obj);#}
{#                    window.location.href ='/admin/ExperimentInfoSectionManagement';#}
{##}
{#                } else {#}
{#                    alert("Entered string did not match. Aborting.");#}
{#                }#}
{#            }#}
{##}
{#        }#}


        function deleteExperimentInfo(id) {
            if (confirm("Really delete experiment info?")) {
                var reply = prompt("Please type the experiment info ID to confirm deletion.", '');
                if (reply == id) {
                    alert("Deleting " + id);
                    var obj = {type: 1, experiment_info_id: id};
                    processAjaxRequest(obj);
                    window.location.href = '/admin/ExperimentInfoSectionManagement';

                } else {
                    alert("Entered ID did not match news ID. Aborting.");
                }
            }

        }

        function redirectTo(URL) {
            window.location.href = '/' + URL;
        }


        function processAjaxRequest(dataObj) {

            dataObj["csrfmiddlewaretoken"] = document.getElementsByName('csrfmiddlewaretoken')[0].value;

            $.ajax({
                type: "POST",
                url: "/en/admin/ExperimentInfoSectionManagement/",
                data: dataObj,
                cache: false,
                async: false,
                success: function (data) {
                    if (data == 'True') {

                    }
                },
                error: function (xhr, textStatus, errorThrown) {
                    alert("Please report this error: " + errorThrown + xhr.status + xhr.responseText);
                }
            });
        }

        function isValidateForm() {
            experimentInfoEn = $('#id_txtExperimentInfoEn');

            if (experimentInfoEn.val() == '') {
                alert("Experiment info in English is required.");
                return false;
            }
            else {
                return true;
            }
        }

    </script>

{% endblock %}