directory/urls.py
"""Copyright Askbot SpA 2014, Licensed under GPLv3 license."""

from django.conf.urls import url
from directory import views
from django.contrib.admin.views.decorators import staff_member_required

urlpatterns = (
    url(r'^$', views.index, name='directory_index'),
    url(r'^list/$', views.list_directory, name='directory_list'),
    url(r'^download-file/(?P<file_name>.*)/$', views.download_file, name='directory_download_file'),
    url(r'^list1/$', staff_member_required(views.list_directory, login_url="/admin/"), name='d_test'),
)

Users/forms.py
from django import forms
from django.utils.translation import activate

from Common import constants

from Users.enums import *
from Users.models import *
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import PasswordChangeForm


class UserInfoForm(forms.Form):
    """
    User info form
    """
    # languageCode= 'en'
    def __init__(self, *args, **kwargs):
        # self.webLanguageId = kwargs.pop(CookieFields.WebsiteLanguageId)
        self.languageCode = kwargs.pop('languageCode','en')
        # excluding the australian and britain english and order by web language
        qs_language = Language.objects.exclude(language_code__in=['en-au','en-gb','pt-br','es-ar','es-mx','es-ni','es-ve']).order_by('language_name_'+self.languageCode)
        qs_country = Country.objects.order_by('country_name_'+self.languageCode)
        super(UserInfoForm, self).__init__(*args, **kwargs)

        self.fields['area_country'].queryset = qs_country
        self.fields['education_country'].queryset = qs_country

        self.fields['area_language'].queryset = qs_language
        self.fields['living_area_language'].queryset = qs_language
        self.fields['native_language'].queryset = qs_language
        self.fields['home_language'].queryset = qs_language
        self.fields['learned_language'].queryset = qs_language


    age = forms.CharField(widget=forms.TextInput(attrs={'class': 'onlyInt number-input form-control'}), required=True)

    gender = forms.ModelChoiceField(queryset=Gender.objects.all(), to_field_name="name",
                                    widget=forms.Select(attrs={'class': 'form-control'}), required=True)

    area_country = forms.ModelChoiceField(queryset=Country.objects.order_by('country_name'),
                                          widget=forms.Select(attrs={'class': 'form-control'}), required=True)

    area_language = forms.ModelChoiceField(queryset=Language.objects.order_by('language_name'),
                                           widget=forms.Select(attrs={'class': 'form-control'}), required=False)

    living_period = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control onlyInt lessThanEqualAge number-input'}), required=True)

    is_lived_in_other_area = forms.BooleanField(widget=forms.RadioSelect(
        choices=((False, constants.CommonConstants.NO_TEXT), (True, constants.CommonConstants.YES_TEXT))),
                                                initial=False, required=False)

    #living_area_language = forms.TypedChoiceField(choices=LanguageList, widget=forms.Select(attrs={'class': 'form-control'}), required=False)
    living_area_language = forms.ModelChoiceField(queryset=Language.objects.order_by('language_name'),
                                                  widget=forms.Select(attrs={'class': 'form-control'}), required=False)
    living_area_period = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control onlyInt lessThanAge number-input'}), required=False)

    is_multilingual = forms.BooleanField(widget=forms.RadioSelect(
        choices=[(False, constants.CommonConstants.NO_TEXT), (True, constants.CommonConstants.YES_TEXT)]),
                                         initial=False, required=False)

    native_language = forms.ModelChoiceField(queryset=Language.objects.all(),
                                             widget=forms.Select(attrs={'class': 'form-control'}), required=False)

    education_country = forms.ModelChoiceField(queryset=Country.objects.order_by('country_name'),
                                               widget=forms.Select(attrs={'class': 'form-control'}), required=False)
    education_time = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control onlyInt lessThanAge number-input'}), required=False)

    home_language = forms.ModelChoiceField(queryset=Language.objects.order_by('language_name'),
                                           widget=forms.Select(attrs={'class': 'form-control'}), required=False)

    learned_language = forms.ModelChoiceField(queryset=Language.objects.order_by('language_name'),
                                              widget=forms.Select(attrs={'class': 'form-control'}), required=False)
    learned_language_time = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control onlyInt lessThanAge number-input'}), required=False)

    # EducationDegree
    highest_education_degree = forms.ModelChoiceField(queryset=EducationDegree.objects.all(),
                                                      widget=forms.Select(attrs={'class': 'form-control'}),
                                                      required=False)
    have_linguistics_degree = forms.BooleanField(widget=forms.RadioSelect(
        choices=[(False, constants.CommonConstants.NO_TEXT), (True, constants.CommonConstants.YES_TEXT)]),
                                                 initial=False, required=False)

    prolific_id = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)


class PasswordChangeCustomForm(PasswordChangeForm):

    old_password = forms.CharField(required=True,
                                   widget=forms.PasswordInput(attrs={
                                        'placeholder': _('OLD_PASSWORD_TEXT')}))
    new_password1 = forms.CharField(required=True,widget=forms.PasswordInput(attrs={
                                        'placeholder': _('NEW_PASSWORD_TEXT')}))
    new_password2 = forms.CharField(required=True,
                                    widget=forms.PasswordInput(attrs={
                                        'placeholder': _("NEW_PASSWORD_CONFIRMATION_TEXT")}))

class PasswordResetConfirmationForm(forms.Form):

    new_password1 = forms.CharField(required=True,widget=forms.PasswordInput(attrs={
                                        'placeholder': _('NEW_PASSWORD_TEXT')}))
    new_password2 = forms.CharField(required=True,
                                    widget=forms.PasswordInput(attrs={
                                        'placeholder': _("NEW_PASSWORD_CONFIRMATION_TEXT")}))

templates/accounts/ChangePassword.html
{% extends "Base.html" %}
{% load staticfiles %}
{% load i18n %}
{% block content %}
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600" rel='stylesheet'
      type='text/css'>
<link href="{% static 'css/fontawesome/css/font-awesome.css' %}" rel="stylesheet" media="screen">
<link href="{% static 'css/registrationpage.css' %}" rel="stylesheet" media="screen">

    <div class="col-lg-12 col-xs-12 task-background" style="padding-top:50px;">
    <div class="row margin-top">
    <div class="col-md-6">
        {% if messages %}
        {% for message in messages %}
        {% if message.tags == 'error' %}
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            {{ message }}
        </div>
        {% endif %}
        {% if message.tags == 'success' %}
        <div class="alert alert-success" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Message:</span>
            {{ message }}
        </div>
        {% endif %}

        {% endfor %}

        {% endif %}

    </div>
</div>

     <div class="container-box" style="height: 330px;">

        <h1>{% trans 'CHANGE_PASSWORD_PAGE_HEADER' %}</h1>
        <form method="post" accept-charset="utf-8">
            {% csrf_token %}
            <label for="id_old_password" class="icon"><i class="fa fa-shield"></i></label>
            {{ form.old_password }}
            <label for="id_password1" class="icon"><i class="fa fa-shield"></i></label>
            {{ form.new_password1 }}
            <label for="id_password2" class="icon"><i class="fa fa-shield"></i></label>
            {{ form.new_password2 }}

            <input type="submit" value="{% trans 'SAVE_PASSWORD_BUTTON_TEXT' %}" class="button" style="background-color: green; width:150px;">
        </form>
    </div>

    </div>
{% endblock %}

templates/accounts/ForgotPassword.html
{% extends "BaseWithoutNavbar.html" %}
{% load staticfiles %}
{% load i18n %}
{% block content %}
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600" rel='stylesheet'
      type='text/css'>
<link href="{% static 'css/fontawesome/css/font-awesome.css' %}" rel="stylesheet" media="screen">
<link href="{% static 'css/registrationpage.css' %}" rel="stylesheet" media="screen">

    <div class="col-lg-12 col-xs-12 task-background" style="padding-top:50px;">
    <div class="row margin-top">
    <div class="col-md-6">
        {% if messages %}
        {% for message in messages %}
        {% if message.tags == 'error' %}
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            {{ message }}
        </div>
        {% endif %}
        {% if message.tags == 'success' %}
        <div class="alert alert-success" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Message:</span>
            {{ message }}
        </div>
        {% endif %}

        {% endfor %}

        {% endif %}

    </div>
</div>

     <div class="container-box" style="height: 330px;">

        <h1>{% trans 'FORGOT_YOUR_PASSWORD_TEXT' %}</h1>
        <form method="post" accept-charset="utf-8">
            {% csrf_token %}
            <label for="email" class="icon"><i class="fa fa-envelope-o"></i></label>
            <input type="text" id="email" name="email" placeholder="{{loginPageConstants.LANDING_PAGE_EMAIL_FIELD_TEXT}}"  />
            <input type="submit" value="{% trans 'SEND_PASSWORD_TEXT' %}" class="button" style="background-color: green; width:150px;">
        </form>
    </div>

    </div>
{% endblock %}

templates/accounts/Login.html
{% extends "Base.html" %}
{% load staticfiles %}
{% block content %}

<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600" rel='stylesheet'
      type='text/css'>
<link href="{% static 'css/fontawesome/css/font-awesome.css' %}" rel="stylesheet" media="screen">
<link href="{% static 'css/registrationpage.css' %}" rel="stylesheet" media="screen">

<style type="text/css">
    /*#id_username {*/
    /*width: 300px;*/
    /*}*/

    /*#id_password {*/
    /*width: 300px;*/
    /*}*/
    /**/
    .container-box {
        height: 275px;
    }

    #loginbar {
        display: none;
    }
</style>


<div class="row">
    <div class="col-md-12 text-right">
        {{loginPageConstants.NewUserQuestion}} <a href="{% url 'userRegistration' %}">{{loginPageConstants.ClickHereForRegistration}}</a>
    </div>
</div>
<div class="row">
    <div class="col-md-12 text-right">
        <b>{{loginPageConstants.LoginUsing}}</b>

            <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">
                <img src="{{ static }}/static/images/socialmedia/facebook.png" style="width:50px;">
            </a>

            <a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">
                <!--Login with Google-->
                <img src="{{ static }}/static/images/socialmedia/google.png" style="width:50px;">
            </a>

            <!--<a href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}">-->
                <!--&lt;!&ndash;Login with Twitter&ndash;&gt;-->
                <!--<img src="{{ static }}/static/images/socialmedia/twitter.png" style="width:50px;">-->
            <!--</a>-->
    </div>
</div>

<div class="row margin-top">
    <div class="col-md-6">

        {% if messages %}
        {% for message in messages %}
        {% if message.tags = 'error' %}
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            {{ message }}
        </div>
        {% endif %}
        {% endfor %}

        {% endif %}

        <!--<div class="alert alert-danger" role="alert">-->
        <!--<a href="#" class="alert-link">...</a>-->
        <!--</div>-->

    </div>
</div>


<div class="content-div col-md-12">
    <div class="container-box">
        <h1>{{loginPageConstants.Login}}</h1>

        <form method="post" accept-charset="utf-8">
            {% csrf_token %}

            <label for="username" class="icon"><i class="fa fa-envelope-o"></i></label>
            <input type="text" id="username" name="username" placeholder="{{loginPageConstants.Email}}"/>
            <!--<label for="name" class="icon"><i class="icon-user"></i></label>-->
            <!--<input type="text" name="name" id="name" placeholder="Name" required/>-->
            <label for="password" class="icon"><i class="fa fa-shield"></i></label>
            <input type="password" id="password" name="password" placeholder="{{loginPageConstants.Password}}"/>
            <input type="hidden" id="next" name="next" value="{{ next }}"/>
            <input type="submit" value="{{loginPageConstants.Login}}" class="button">
        </form>
    </div>
</div>

{% endblock %}

templates/accounts/Logout.html
{% extends "Base.html" %}
{% block content %}


<div class="container content-div margin-top">

        <div class="row margin-top ">
            <div class="col-md-12">
               {% trans "LOGOUT_TEXT" %}
            </div>
        </div>

</div>
{% endblock %}

templates/accounts/Registration.html
{% extends "Base.html" %}
{% load staticfiles %}
{% block content %}

<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600" rel='stylesheet'
      type='text/css'>
<link href="{% static 'css/fontawesome/css/font-awesome.css' %}" rel="stylesheet" media="screen">
<link href="{% static 'css/registrationpage.css' %}" rel="stylesheet" media="screen">

<div class="content-div col-lg-12 col-xs-12 task-background" style="padding-top:50px;">

    <div class="row margin-top">
    <div class="col-md-6">
        {% if messages %}
        {% for message in messages %}
        {% if message.tags == 'error' %}
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            {{ message }}
        </div>
        {% endif %}
        {% endfor %}

        {% endif %}

    </div>
</div>

    <div class="container-box">

        <h1>{{loginPageConstants.USER_REGISTRATION_PAGE_HEADER}}</h1>
        <form method="post" accept-charset="utf-8">
            {% csrf_token %}
            <label for="username" class="icon"><i class="fa fa-flag"></i></label>
            <input type="text" id="username" name="username" placeholder="{{loginPageConstants.LANDING_PAGE_USERNAME_FIELD_TEXT}}" />

            <label for="email" class="icon"><i class="fa fa-envelope-o"></i></label>
            <input type="text" id="email" name="email" placeholder="{{loginPageConstants.LANDING_PAGE_EMAIL_FIELD_TEXT}}" />
            <label for="password" class="icon"><i class="fa fa-shield"></i></label>
            <input type="password" id="password" name="password" placeholder="{{loginPageConstants.LANDING_PAGE_PASSWORD_FIELD_TEXT}}" />
            <label for="confirmPassword" class="icon"><i class="fa fa-shield"></i></label>
            <input type="password" id="confirmPassword" name="confirmPassword" placeholder="{{loginPageConstants.USER_REGISTRATION_PAGE_CONFIRM_PASSWORD_FIELD_TEXT}}"/>

            <p style="margin-left: 15px; font-size: 12px;line-height:1.5;">
                {{loginPageConstants.INFORMED_CONSENT_MESSAGE_TEXT}}
                <br> {{ loginPageConstants.INFORMED_CONSENT_I_AGREE_TEXT }}
                <input type="checkbox" id="chkInformationConsent" name="chkInformationConsent" checked="checked" />
            </p>

            <p style="margin-left: 15px; font-size: 12px;line-height:0.2;">
                <a href="/InformedConsent/" target="_blank"> {{ loginPageConstants.INFORMED_CONSENT_PAGE_LINK_TEXT }} </a>
            </p>

            <p style="margin-left: 15px;font-size: 12px;line-height:1.5;">{{loginPageConstants.USER_REGISTRATION_PAGE_NEWS_LETTER_QUESTION}}
                <input type="checkbox" id="chkNewsletter" name="chkNewsLetter" checked="checked" />
            </p>

            <input type="submit" value="{{loginPageConstants.LANDING_PAGE_REGISTER_BUTTON_TEXT}}" class="button" style="background-color: green;">
        </form>
    </div>

</div>

{% endblock %}

templates/accounts/ResetForgotPassword.html
{% extends "Base.html" %}
{% load staticfiles %}
{% load i18n %}
{% block content %}
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600" rel='stylesheet'
      type='text/css'>
<link href="{% static 'css/fontawesome/css/font-awesome.css' %}" rel="stylesheet" media="screen">
<link href="{% static 'css/registrationpage.css' %}" rel="stylesheet" media="screen">

    <div class="col-lg-12 col-xs-12 task-background" style="padding-top:50px;">
    <div class="row margin-top">
    <div class="col-md-6">
        {% if messages %}
        {% for message in messages %}
        {% if message.tags == 'error' %}
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            {{ message }}
        </div>
        {% endif %}
        {% if message.tags == 'success' %}
        <div class="alert alert-success" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Message:</span>
            {{ message }}
        </div>
        {% endif %}

        {% endfor %}

        {% endif %}

    </div>
</div>

     <div class="container-box" style="height: 330px;">

        <h1>{% trans 'RESET_PASSWORD_PAGE_HEADER' %}</h1>
        <form method="post" accept-charset="utf-8">
            {% csrf_token %}
            <label for="id_password1" class="icon"><i class="fa fa-shield"></i></label>
            {{ form.new_password1 }}
            <label for="id_password2" class="icon"><i class="fa fa-shield"></i></label>
            {{ form.new_password2 }}

            <input type="submit" value="{% trans 'RESET_PASSWORD' %}" class="button" style="background-color: green; width:150px;">
        </form>
    </div>

    </div>
{% endblock %}